# Generated by Django 2.1.7 on 2019-03-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='group',
            new_name='category',
        ),
    ]
