# Generated by Django 2.1.7 on 2019-03-05 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20190304_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(default='PRODUCT', max_length=250),
        ),
        migrations.AlterField(
            model_name='category',
            name='customer_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='customer_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='seller',
            name='customer_id',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='seller',
            name='mobile_no',
            field=models.IntegerField(),
        ),
    ]
